typography_spectrum: 0.50771
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5246292597148567
  lightness: 0.18512447667308152
  saturation: 0.85124556790106
  rhythmicContrast: 0.9453730499371886
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Depressão Pós Parto
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Triste
    id: 9b393763-6c42-4982-91c4-b392a43cf74c
    type: content
favicon: null
title: Depressão Pós Parto
description: O que vc está sentindo?
purpose: []
